### ISSUE TITLE
APIRule v2alpha1 UI extensions

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#1353]
**Description**

Extend Busola extensions to support APIRule v2alpha1. APIRule v2alpha1 implementation is complete and testing API and migration procedure is open. It is expected that there will be no significant changes introduced and v2alpha1 will be promoted to stable v2 version. Considering longer period of testing window it was decided to add respective UIs in Kyma dashboard. As a user i want to be able to managed not supported version of APIRule via Kyma Dashboard. 

**PR**
- https://github.com/kyma-project/api-gateway/pull/1374

TODO:
- [x] UI form, list and details implemented
- [x] UI Tests for lists implemented

ACs:
- [x] corresponding views for APIRule v2alpha1 created
- [x] only APIRule v2alpha1 CRs are present on list view of v2alpha1
- [x] only APIRule v1beta1CRs are present on list view of v1beta1

stretch: UI test for checking lists if they display right APIRules

**Reasons**

**DoD:**
~~- [ ] Provide unit and integration tests.~~
~~- [ ] Provide documentation.~~
~~- [ ] Verify if the solution works for both open-source Kyma and SAP BTP, Kyma runtime.~~
~~- [ ] If you changed the resource limits, explain why it was needed.~~
~~- [ ] Verify that your contributions don't decrease code coverage. If they do, explain why this is the case.~~
- [x] Add release notes.

**Attachments**
part of: #939 
https://github.com/kyma-project/api-gateway/tree/main/config/ui-extensions/apirules

**Comment by triffer** [comment]
Some assumptions were made while implementing the UI, because validation doesn't exist any longer or Busola doesn't allow mapping in the UI that would be required for some use cases.

- Removed host link in details metadata, because v2alpha1 will support multiple hosts in the future. Additionally, Host was moved to the `General` data because it is not metadata.
- Removed warning Gateway must be in the format '{NAMESPACE}/{NAME}' because validation of v2alpha1 covers that already
- Removed warning Disabling custom CORS Policy is not recommended. Consider setting up CORS yourself, because the default CORS config for v2alpha1 changed to a secure by default config.
- Removed many UI validations, because we should avoid duplicate validation as we already validate this in the CRD or backend and it makes UI config maps much harder to maintain.
- Simplified v2alpha1 hosts in the form to be a list of values, because it's not possible to bind the form to the first entry of a list
