### ISSUE TITLE
APIRule v1beta1 notification in Kyma Dashboard

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#1423]
**Description**

Implement notification in Kyma dashboard informing about APIRule v1beta1 deprecation and migration. Kyma Dashboard feature card should be used. Notification should contain links do deprecation and deletion notes and to migration blog posts. 

ACs:
- [x] notification about APIRule v1beta1 is visible in Kyma dashboard

TODOs:
- [x] Add new element in the UI
- [x] Create PR in Busola to fix issue with illustration and banner slot placement in resource views
- [x] Add release notes

PRs:
- https://github.com/kyma-project/busola/pull/3468
- https://github.com/kyma-project/busola/pull/3470
- https://github.com/kyma-project/api-gateway/pull/1448

**Reasons**

**DoD:**
~~- [ ] Provide unit and integration tests.~~
~~- [ ] Provide documentation.~~
~~- [ ] Verify if the solution works for both open-source Kyma and SAP BTP, Kyma runtime.~~
~~- [ ] If you changed the resource limits, explain why it was needed.~~
~~- [ ] Verify that your contributions don't decrease code coverage. If they do, explain why this is the case.~~
~~- [ ] Add release notes.~~

**Attachments**
Deprecation note: https://help.sap.com/whats-new/cf0cb2cb149647329b5d02aa96303f56?q=API+Gateway+module:+Deprecation+of+APIRule+v1beta1&locale=en-US&Software_Lifecycle=Deprecated
Deletion note: https://help.sap.com/whats-new/cf0cb2cb149647329b5d02aa96303f56?locale=en-US&Component=Kyma+Runtime&Valid_as_Of=2025-05-12:2025-05-12
https://community.sap.com/t5/technology-blogs-by-sap/sap-btp-kyma-runtime-apirule-migration-ory-oathkeeper-based-oauth2-handlers/ba-p/13896184
https://community.sap.com/t5/technology-blogs-by-sap/sap-btp-kyma-runtime-apirule-migration-noauth-and-jwt-handlers/ba-p/13882833

**Comment by triffer** [comment]
Since it is not specified where the new element should be displayed, I assumed that it should be displayed like the other FeatureCards in the banner slot in the ClusterOverview:![Image](https://github.com/user-attachments/assets/95942bf0-7770-4ffc-b654-1442a5380095)

If this is not desired, another option would be to display the FeatureCard in the details of an APIRule:
![Image](https://github.com/user-attachments/assets/9e599903-35e2-4c52-b847-e6aa1cedcb40)

The display in the header of the resource list is unfortunately not so well implemented in Busola, as the element is then hidden in a meatballs menu and is also not displayed well:
![Image](https://github.com/user-attachments/assets/44715f6a-59d7-4025-ac1a-544e5f52627d)


Unfortunately, the default FeatureCard contains a "module" image that can be seen in the attached screenshots. There is only a second option available called "AI" and that will replace the bricks with a robot: ![Image](https://github.com/user-attachments/assets/4cb18741-3b4e-45ae-98c7-7be708e24a0f)

Also out of the box, the FeatureCard limits the number of possible buttons to two, but it is possible to work around this by nesting the buttons in a panel element.

**Comment by triffer** [comment]
It is planned that the changes in Busola will be available on Monday 11th November on all environments.
