### ISSUE TITLE
Provide support for configuring request timeout in APIRule

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/api-gateway#169]
For long-running requests, the getway timout occurs. Currently, there is no way to control the timeout parameter via APIRule.

**Comment by videlov** [comment]
As discussed, we would like to introduce it per service / API-Rule for most flexibility.

**Comment by ptesny** [comment]
As it looks like certain target system may be slow to respond; at least initially; thus being able to add a request timeout to the virtual service of an API rule would make like of business developers way easier

**Comment by ptesny** [comment]
my recent testing prove that the 180 seconds HTTP timeout on the virtual service side has no effect;

**Comment by ptesny** [comment]
It seems that for the virtual service timeout to work the istio ingress gateway LB timeout needs to adjusted accordingly, for instance:
AWS:
```
$ kubectl annotate svc -n istio-system istio-ingressgateway service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout="3600" 
service/istio-ingressgateway annotated
```
AZURE:
```
$ kubectl annotate svc -n istio-system istio-ingressgateway service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout="30" 
service/istio-ingressgateway annotated
```

**Comment by triffer** [comment]
We investigated further where timeouts can occur and how we can change this configuration.
There are different levels where a timeout can occur.

### Timeout in Virtual Service
This is set by the api-gateway to 180s for all virtual services.

As [already discussed](https://github.com/kyma-project/api-gateway/issues/169#issuecomment-1387192208), it would be useful if this can be configured in the APIRule.

### Timeout caused by Ory Oathkeeper
If the workload is secured by Oathkeeper, e.g. by using the noop, oauth2 or jwt access strategy, there is a default timeout of 120s. Once the 120s is reached, Oathkeeper considers this request as failed. Istio then retries the request and sends it to Oathkeeper again until the default value of two retries or the timeout configured in the virtual service is reached.

It is not possible to disable the timeout in Oathkeeper, so it would be best to set this timeout to a very high value such as 2 hours, as the virtual service will ensure that the timeout is handled correctly.

### Timeout in Hyperscaler-specific load balancers
We checked the behaviour for long-running requests for AWS, GCP and Azure. For GCP and Azure, we were able to successfully run a one-hour request after exposing the workload with a virtual service with a configured timeout of 2 hours. 

For AWS, we were able to increase the default timeout of 60s by using the custom annotation `service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout` on the Istio Ingressgateway load balancer. Since we have a default timeout configured in the virtual service it would be safe to set the timeout to the maximum of 4000s.

We also verified how the annotation is retained during the reconciliation. We verified on a SKR cluster that the annotation on istio-ingressgateway is not removed by the reconciliation. Furthermore, even when Istio was updated by the reconciler, the annotation was not removed.

## Next Steps
- Make the virtual service timeout configurable through the APIRule
- Increase the default timeout in Ory Oathkeeper
- For virtual service timeouts to work as expected in AWS, we need to ensure that the Istio ingress gateway has the timeout annotation. For simplicity, it would be easier to always set it to 4000s and document this limitation.

**Comment by ptesny** [comment]
> Timeout in Hyperscaler-specific load balancers
We checked the behaviour for long-running requests for AWS, GCP and Azure. For GCP and Azure, we were able to successfully run a one-hour request after exposing the workload with a virtual service with a configured timeout of 2 hours.

What is the annotation syntax for AZure ?

**Comment by triffer** [comment]
> What is the annotation syntax for AZure ?

The annotation to configure timeouts for Azure Load balancer is `service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout` documented [here](https://cloud-provider-azure.sigs.k8s.io/topics/loadbalancer/). However, setting this annotation had no effect on the timeout, as we were able to execute a one-hour request without any annotation.

**Comment by ptesny** [comment]
@triffer , Would you agree that as of 2.13 version managed kyma onwards with AZURE the real timeout is that of ORY equal 120 seconds?

**Comment by triffer** [comment]
@ptesny 
Yes, the default timeout of Oathkeeper is the limiting factor. But even though Oathkeeper will timeout after 120s, the request will timeout after 180s (defined in the virtual service), since Istio will retry the failed request.

To better understand maybe an example better helps understanding this:
- Request is sent to host exposed by virtual service
- Request is routed to Destination Oathkeeper with a timeout of 180s and a default retry of 2
- After 120s Oathkeeper responses with timeout
- Retry configuration in virtual service causes request to Oathkeeper to be sent again
- After 180s virtual service sends timeout of the request

**Comment by ptesny** [comment]
@triffer , thank you; 
in the end what we need to be able to set an HTTP request timeout value....any value.... and that should trigger the alignment of these various timeout values along the entire chain.....

**Comment by ptesny** [comment]
@triffer , I think it would make sense to align the Ory Oatkeeper and API rule managed-Virtual Service timeouts.

**Comment by ptesny** [comment]
@triffer how about excluding the API rule managed Virtual service HTTP timeout from being reconciled? This way there is no need to develop any additional UI with the API rule CRD.

**Comment by triffer** [comment]
> I think it would make sense to align the Ory Oatkeeper and API rule managed-Virtual Service timeouts.

We configured a rather high timeout for Ory Oathkeeper since it's a global timeout. This means we would need to update the timeout of the Oathkeeper configuration always depending on the highest timeout configured in a virtual service. Also we are moving away from Oathkeeper and 60 min is already a very long timeout for requests.

> how about excluding the API rule managed Virtual service HTTP timeout from being reconciled? This way there is no need to develop any additional UI with the API rule CRD.

I feel like it would be better to have this configured and controlled by the APIRule. Ignoring the virtual service from the HTTP timeout might be not so obvious. So from the UX point of view I think making it configurable with a good default is the better approach.

**Comment by ptesny** [comment]
> I feel like it would be better to have this configured and controlled by the APIRule. Ignoring the virtual service from the HTTP timeout might be not so obvious. So from the UX point of view I think making it configurable with a good default is the better approach.

What would be the ETA ?

**Comment by strekm** [comment]
@ptesny we do not have it on our roadmap yet. so no ETA yet. we might consider introducing it when we will start working on api-gateway module

**Comment by ptesny** [comment]
thank you. which kyma release it is going to be in ?

**Comment by videlov** [comment]
> thank you. which kyma release it is going to be in ?

Kyma 1.18
