### ISSUE TITLE
Support mTLS in default certificate 

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#832]
**Description**

API Gateway module comes with default domain, simple TLS gateway and certificate. To support mTLS in early development phase add *.mtls.{kyma-domain} to DNS Names of issued default Certificate CR. This way developers can reuse this certificate to implement in their own mTLS gateway. This would ease setup of mTLS in Kyma. Managed Kyma users can reuse Kyma default domain and certificate in development. This approach should not be used in production setup. Following scenario should be possible:
- enhance default Kyma certificate with additional root certificate 
- create mTLS gateway for *.mtls.{kyma-domain} reusing default Kyma certificate
- expose httpbin on httpbin.mtls.{kyma-domain}
- call httpbin workload with valid certificate
- inspect XFCC-header on httpbin side

TODO:
- [ ] dbl check if dns names is needed (if mtls dns name is need implement, otherwise nothing to do here)
- [ ] check staging and production envs for usage of *.mtls.{kyma-domain}
- [ ] consult @TorstenD-SAP on reusing Kyma default certificate

ACs:
- [ ] developer can setup mTLS gateway reusing default Kyma certificate
- [ ] developer can add secret with root certificate
- [ ] simple TLS gateway is not changed
- [ ] note in documentation that this is for development purposes only

**Reasons**

Easy implementation of mTLS in Kyma.

**DoD:**
- [x] Provide unit and integration tests.
- [x] Provide documentation.
- [x] Verify if the solution works for both open-source Kyma and SAP BTP, Kyma runtime.
- [x] If you changed the resource limits, explain why it was needed.
- [x] Verify that your contributions don't decrease code coverage. If they do, explain why this is the case.
- [x] Add release notes.

**Attachments**

**Comment by Ressetkk** [comment]
Okay, so I'm going to sum up my R&D work around supporting mTLS.
I've set up some additional configuration and confirmed, that kyma-tls certificate can be indeed extended. However I've noticed some additional configuration that is applied around default gateway that api-gateway creates. In managed offering additionally there is already self-signed cert created outside of the bounds of api-gateway default gateway. I've confirmed it with @ebensom and @gczuczy.

To make mTLS possible in basic spec some additional configuration is needed:
* Create (or buy) Root CA certificate
* Create and sign server certificate and add it as secret
* Create and sign client certificates
* Create gateway, or extend existing gateway with a server pointing to some domain, with server certificate
* Create secret containing our Root CA cert with naming convention described in [Istio reference](https://istio.io/latest/docs/reference/config/networking/gateway/#ServerTLSSettings)
* Create virtual service that uses mtls-gateway and points to subdomain that we want to have our workload exposed on

Since we cannot really touch the existing cacert secret that's created without breaking external integration I'm afraid, the best idea would be to set up a configuration in APIGateway CR that manages basic mTLS gateway with Root CA either provided in a CR, or automatically generated at runtime.

On api-gateway side what can be theoretically handled:
* Create a LE certificate for mTLS subdomain `*.mtls.{{ .DOMAIN }}` with a name like `kyma-mtls-gateway`
* Get certificate from the CR spec, or if empty, generate self-signed Root CA cert and put it into secret, like `kyma-mtls-gateway-cacert`
* Provide option to retrieve a cert and key for manual generation of client certs, or have an ability to feed the secret into cert-manager or Gardener's cert management controller to serve as custom CA issuer (2nd part optional since it's heavy configuration dependent)

The following configuration could be handled in an APIGateway CR and could be followed with the spec below
```yaml
spec:
  mtls-gateway: # or camelCase
    enabled: true # set if gateway needs to be created
    host: "" # optional - if empty then default wildcard gateway domain is used with *.mtls. subdomain
    cacert: # optional, if empty then generate self-signed Root CA cert
      cert: "" # base64 encoded root ca cert
      key: "" # base64 encoded root ca private key
```

Example roughly followed by https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/

1. Create Root CA cert
```sh
openssl req -x509 -sha256 -nodes -days 1000 -newkey rsa:2048 -subj '/O=Kyma /CN=SelfSigned' -keyout cacert.key -out cacert.crt
```
2.  Create client CertificateSigningRequest
```sh
openssl req -out client.csr -newkey rsa:2048 -nodes -keyout client.key -subj "/CN=$HOST/O=Kyma"
```
3. Generate new client certificate
```sh
openssl x509 -req -sha256 -days 365 -CA cacert.crt -CAkey cacert.key -set_serial 1 -in client.csr -out client.crt
```
4. (Gardener-specific) Generate a new Certificate for `*.mtls.$DOMAIN`
```sh
cat <<EOF | kubectl apply -f -
apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: kyma-mtls-cert
  namespace: istio-system
spec:
  commonName: '*.mtls.$DOMAIN'
  secretName: kyma-mtls-certs
  secretRef:
    name: kyma-mtls-certs
    namespace: istio-system
EOF
```
5. Create new mTLS gateway in kyma-system for wildcard subdomain `*.mtls.$DOMAIN`
```sh
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kyma-mtls-gateway
  namespace: kyma-system
  labels:
    app.kubernetes.io/name: api-gateway-operator
    app.kubernetes.io/instance: api-gateway-operator-default
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: api-gateway
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: mtls
        protocol: HTTPS
      tls:
        mode: MUTUAL
        credentialName: kyma-mtls-certs
      hosts:
        - "*.mtls.$DOMAIN"
EOF
```
6. Create httpbin Deployment and service
7. Create APIRule that exposes httpbin service using `kyma-mtls-gateway` on a hostname `httpbin.mtls.$DOMAIN`
8. Validate if connection to `httpbin.mtls.$DOMAIN` gets accepted using curl with provided client.crt and client.key using the following command
```sh
curl --cert client.crt --key client.key --cacert cacert.crt -X GET https://httpbin.mtls.be63f8c.stage.kyma.ondemand.com/status/418


    -=[ teapot ]=-

       _...._
     .'  _ _ `.
    | ."` ^ `". _,
    \_;`"---"`|//
      |       ;/
      \_     _/
        `"""`
```

So for complete scope of this task the AC needs to be adjusted:
* Extend APIGateway CR for optional mTLS gateway enablement
* Developer can provide their own Root CA cert in a CR or SelfSigned cert would be generated
* mTLS gateway is independent from default gateway
* Documentation gets updated with a tutorial how to enable mTLS gateway

Question - what about self-signed server certs? Should we allow them to be somehow provisioned and used for server certificate validation when mTLS gateway is created? Or is it out of scope? I mean to have both server and client certs be signed by the same CA used in mtls gateway config.

**Comment by Ressetkk** [comment]
Upon further discussion we've decided that we'll provide the documentation on how to provision separate mTLS gateway with required separate certificate and CA configuration.
The certificate does not need extension for a subdomain, however there is already provisioned cacert secret managed by application-connector, so we can't allow injecting custom CA cert for validating client certificates. Therefore user still needs to provision separate certificate.

We will not extend default gateway certificate and we will not change the default configuration.
